[package]
name = "timew_ical"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.41"
clap = { version = "4.5.40", features = ["derive"] }
icalendar = "0.17.1"
parse_datetime = "0.10.0"
serde = "1.0.219"
